clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  syntax-php7.0:
    image: nextcloudci/php7.0:php7.0-19
    environment:
    - APP_NAME=workflow_script
    - CORE_BRANCH=master
    - DB=sqlite
    commands:
    # Pre-setup steps
    - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
    - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
    - cd ../server
    - composer install
    - ./lib/composer/bin/parallel-lint apps/$APP_NAME/
    when:
      matrix:
        TESTS: syntax-php7.0
  signed-off-check:
    image: nextcloudci/php7.0:php7.0-19
    environment:
      - APP_NAME=workflow_script
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php ./build/signed-off-checker.php
    secrets: [ github_token ]
    when:
      matrix:
        include:
        - TESTS: syntax-php7.0
        - TESTS: signed-off-check
matrix:
  include:
    - TESTS: signed-off-check
